package com.github.care.wx.mp.dao.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FootMatch implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.user_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.field
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.match_name
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private String matchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.parties
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private String parties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.play_type
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private String playType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.bet
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private String bet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.bet_adds
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private BigDecimal betAdds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.reason
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.result
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.plan_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Long planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.create_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_match.update_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.id
     *
     * @return the value of foot_match.id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.id
     *
     * @param id the value for foot_match.id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.user_id
     *
     * @return the value of foot_match.user_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.user_id
     *
     * @param userId the value for foot_match.user_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.field
     *
     * @return the value of foot_match.field
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.field
     *
     * @param field the value for foot_match.field
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.match_name
     *
     * @return the value of foot_match.match_name
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public String getMatchName() {
        return matchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.match_name
     *
     * @param matchName the value for foot_match.match_name
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setMatchName(String matchName) {
        this.matchName = matchName == null ? null : matchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.parties
     *
     * @return the value of foot_match.parties
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public String getParties() {
        return parties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.parties
     *
     * @param parties the value for foot_match.parties
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setParties(String parties) {
        this.parties = parties == null ? null : parties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.play_type
     *
     * @return the value of foot_match.play_type
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public String getPlayType() {
        return playType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.play_type
     *
     * @param playType the value for foot_match.play_type
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setPlayType(String playType) {
        this.playType = playType == null ? null : playType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.bet
     *
     * @return the value of foot_match.bet
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public String getBet() {
        return bet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.bet
     *
     * @param bet the value for foot_match.bet
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setBet(String bet) {
        this.bet = bet == null ? null : bet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.bet_adds
     *
     * @return the value of foot_match.bet_adds
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public BigDecimal getBetAdds() {
        return betAdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.bet_adds
     *
     * @param betAdds the value for foot_match.bet_adds
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setBetAdds(BigDecimal betAdds) {
        this.betAdds = betAdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.reason
     *
     * @return the value of foot_match.reason
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.reason
     *
     * @param reason the value for foot_match.reason
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.result
     *
     * @return the value of foot_match.result
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.result
     *
     * @param result the value for foot_match.result
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.plan_id
     *
     * @return the value of foot_match.plan_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.plan_id
     *
     * @param planId the value for foot_match.plan_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.create_time
     *
     * @return the value of foot_match.create_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.create_time
     *
     * @param createTime the value for foot_match.create_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_match.update_time
     *
     * @return the value of foot_match.update_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_match.update_time
     *
     * @param updateTime the value for foot_match.update_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", field=").append(field);
        sb.append(", matchName=").append(matchName);
        sb.append(", parties=").append(parties);
        sb.append(", playType=").append(playType);
        sb.append(", bet=").append(bet);
        sb.append(", betAdds=").append(betAdds);
        sb.append(", reason=").append(reason);
        sb.append(", result=").append(result);
        sb.append(", planId=").append(planId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}
