package com.github.care.wx.mp.dao.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FootPlan implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_plan.id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_plan.user_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_plan.name
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_plan.info
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_plan.monery
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private BigDecimal monery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_plan.create_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_plan.update_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_plan.show_start_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Date showStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foot_plan.show_end_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Date showEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_plan.id
     *
     * @return the value of foot_plan.id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_plan.id
     *
     * @param id the value for foot_plan.id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_plan.user_id
     *
     * @return the value of foot_plan.user_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_plan.user_id
     *
     * @param userId the value for foot_plan.user_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_plan.name
     *
     * @return the value of foot_plan.name
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_plan.name
     *
     * @param name the value for foot_plan.name
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_plan.info
     *
     * @return the value of foot_plan.info
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_plan.info
     *
     * @param info the value for foot_plan.info
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_plan.monery
     *
     * @return the value of foot_plan.monery
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public BigDecimal getMonery() {
        return monery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_plan.monery
     *
     * @param monery the value for foot_plan.monery
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setMonery(BigDecimal monery) {
        this.monery = monery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_plan.create_time
     *
     * @return the value of foot_plan.create_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_plan.create_time
     *
     * @param createTime the value for foot_plan.create_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_plan.update_time
     *
     * @return the value of foot_plan.update_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_plan.update_time
     *
     * @param updateTime the value for foot_plan.update_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_plan.show_start_time
     *
     * @return the value of foot_plan.show_start_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Date getShowStartTime() {
        return showStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_plan.show_start_time
     *
     * @param showStartTime the value for foot_plan.show_start_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setShowStartTime(Date showStartTime) {
        this.showStartTime = showStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foot_plan.show_end_time
     *
     * @return the value of foot_plan.show_end_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Date getShowEndTime() {
        return showEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foot_plan.show_end_time
     *
     * @param showEndTime the value for foot_plan.show_end_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setShowEndTime(Date showEndTime) {
        this.showEndTime = showEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", name=").append(name);
        sb.append(", info=").append(info);
        sb.append(", monery=").append(monery);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", showStartTime=").append(showStartTime);
        sb.append(", showEndTime=").append(showEndTime);
        sb.append("]");
        return sb.toString();
    }
}
