package com.github.care.wx.mp.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class ForumMessage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_message.id
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_message.user_id
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_message.forum_info_id
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    private Long forumInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_message.info
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_message.hot
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    private Long hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_message.status
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_message.create_time
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum_message.update_time
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_message.id
     *
     * @return the value of forum_message.id
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_message.id
     *
     * @param id the value for forum_message.id
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_message.user_id
     *
     * @return the value of forum_message.user_id
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_message.user_id
     *
     * @param userId the value for forum_message.user_id
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_message.forum_info_id
     *
     * @return the value of forum_message.forum_info_id
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public Long getForumInfoId() {
        return forumInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_message.forum_info_id
     *
     * @param forumInfoId the value for forum_message.forum_info_id
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public void setForumInfoId(Long forumInfoId) {
        this.forumInfoId = forumInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_message.info
     *
     * @return the value of forum_message.info
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_message.info
     *
     * @param info the value for forum_message.info
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_message.hot
     *
     * @return the value of forum_message.hot
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public Long getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_message.hot
     *
     * @param hot the value for forum_message.hot
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public void setHot(Long hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_message.status
     *
     * @return the value of forum_message.status
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_message.status
     *
     * @param status the value for forum_message.status
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_message.create_time
     *
     * @return the value of forum_message.create_time
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_message.create_time
     *
     * @param createTime the value for forum_message.create_time
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum_message.update_time
     *
     * @return the value of forum_message.update_time
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum_message.update_time
     *
     * @param updateTime the value for forum_message.update_time
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", forumInfoId=").append(forumInfoId);
        sb.append(", info=").append(info);
        sb.append(", hot=").append(hot);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}