package com.github.care.wx.mp.dao.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PayInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.open_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.plan_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Long planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.monery
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private BigDecimal monery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.third_no
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private String thirdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.create_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.update_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_info
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.id
     *
     * @return the value of pay_info.id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.id
     *
     * @param id the value for pay_info.id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.open_id
     *
     * @return the value of pay_info.open_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.open_id
     *
     * @param openId the value for pay_info.open_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.plan_id
     *
     * @return the value of pay_info.plan_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.plan_id
     *
     * @param planId the value for pay_info.plan_id
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.monery
     *
     * @return the value of pay_info.monery
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public BigDecimal getMonery() {
        return monery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.monery
     *
     * @param monery the value for pay_info.monery
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setMonery(BigDecimal monery) {
        this.monery = monery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.third_no
     *
     * @return the value of pay_info.third_no
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public String getThirdNo() {
        return thirdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.third_no
     *
     * @param thirdNo the value for pay_info.third_no
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setThirdNo(String thirdNo) {
        this.thirdNo = thirdNo == null ? null : thirdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.create_time
     *
     * @return the value of pay_info.create_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.create_time
     *
     * @param createTime the value for pay_info.create_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.update_time
     *
     * @return the value of pay_info.update_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.update_time
     *
     * @param updateTime the value for pay_info.update_time
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", openId=").append(openId);
        sb.append(", planId=").append(planId);
        sb.append(", monery=").append(monery);
        sb.append(", thirdNo=").append(thirdNo);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}
