package com.github.care.wx.mp.dao.mapper;

import com.github.care.wx.mp.dao.entity.FootMatch;
import com.github.care.wx.mp.dao.entity.FootMatchCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FootMatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int countByExample(FootMatchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int deleteByExample(FootMatchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int insert(FootMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int insertSelective(FootMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    List<FootMatch> selectByExampleWithRowbounds(FootMatchCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    List<FootMatch> selectByExample(FootMatchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    FootMatch selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") FootMatch record, @Param("example") FootMatchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int updateByExample(@Param("record") FootMatch record, @Param("example") FootMatchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int updateByPrimaryKeySelective(FootMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_match
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int updateByPrimaryKey(FootMatch record);
}
