package com.github.care.wx.mp.dao.mapper;

import com.github.care.wx.mp.dao.entity.FootPlan;
import com.github.care.wx.mp.dao.entity.FootPlanCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FootPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int countByExample(FootPlanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int deleteByExample(FootPlanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int insert(FootPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int insertSelective(FootPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    List<FootPlan> selectByExampleWithRowbounds(FootPlanCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    List<FootPlan> selectByExample(FootPlanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    FootPlan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") FootPlan record, @Param("example") FootPlanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int updateByExample(@Param("record") FootPlan record, @Param("example") FootPlanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int updateByPrimaryKeySelective(FootPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_plan
     *
     * @mbggenerated Fri Aug 31 15:45:23 CST 2018
     */
    int updateByPrimaryKey(FootPlan record);
}
