package com.github.care.wx.mp.dao.mapper;

import com.github.care.wx.mp.dao.entity.ForumMessage;
import com.github.care.wx.mp.dao.entity.ForumMessageCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ForumMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    int countByExample(ForumMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    int deleteByExample(ForumMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    int insert(ForumMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    int insertSelective(ForumMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    List<ForumMessage> selectByExampleWithRowbounds(ForumMessageCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    List<ForumMessage> selectByExample(ForumMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    ForumMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") ForumMessage record, @Param("example") ForumMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    int updateByExample(@Param("record") ForumMessage record, @Param("example") ForumMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    int updateByPrimaryKeySelective(ForumMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_message
     *
     * @mbggenerated Wed Sep 12 17:14:51 CST 2018
     */
    int updateByPrimaryKey(ForumMessage record);
}