package com.github.care.wx.mp.dao.mapper;

import com.github.care.wx.mp.dao.entity.ForumInfo;
import com.github.care.wx.mp.dao.entity.ForumInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ForumInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    int countByExample(ForumInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    int deleteByExample(ForumInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    int insert(ForumInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    int insertSelective(ForumInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    List<ForumInfo> selectByExampleWithBLOBsWithRowbounds(ForumInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    List<ForumInfo> selectByExampleWithBLOBs(ForumInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    List<ForumInfo> selectByExampleWithRowbounds(ForumInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    List<ForumInfo> selectByExample(ForumInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    ForumInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") ForumInfo record, @Param("example") ForumInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ForumInfo record, @Param("example") ForumInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    int updateByExample(@Param("record") ForumInfo record, @Param("example") ForumInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    int updateByPrimaryKeySelective(ForumInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ForumInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum_info
     *
     * @mbggenerated Tue Sep 04 11:16:43 CST 2018
     */
    int updateByPrimaryKey(ForumInfo record);
}